# Generated by Django 5.0.2 on 2024-02-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('characters', '0002_lifepathquestion_lifepathanswer'), ('characters', '0003_remove_lifepathanswer_character_and_more'), ('characters', '0004_characterlifepathanswer_character_lifepath_answers')]

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifepathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('followup_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_questions', to='characters.lifepathquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LifepathAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('followup_question_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.lifepathquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifepath_answers', to='characters.lifepathquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLifepathAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.lifepathanswer')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='lifepath_answers',
            field=models.ManyToManyField(related_name='characters', through='characters.CharacterLifepathAnswer', to='characters.lifepathanswer'),
        ),
    ]
