# Generated by Django 5.0.2 on 2024-02-18 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_lifepathquestion_lifepathanswer_squashed_0004_characterlifepathanswer_character_lifepath_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifepathquestion',
            name='is_first_question',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LifepathConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_point', to='characters.lifepathquestion')),
            ],
        ),
    ]
